return {
  box = {},
  defeatedTrainers = {},
  flags = {},
  inventory = {
    BICYCLE = 1,
    BOULDERBADGE = 1,
    CASCADEBADGE = 1,
    EARTHBADGE = 1,
    FULL_HEAL = 10,
    FULL_RESTORE = 20,
    HM01 = 1,
    HM02 = 1,
    HM03 = 1,
    HM04 = 1,
    HM05 = 1,
    MARSHBADGE = 1,
    MAX_POTION = 20,
    RAINBOWBADGE = 1,
    RARE_CANDY = 10,
    REVIVE = 10,
    SOULBADGE = 1,
    THUNDERBADGE = 1,
    ULTRA_BALL = 30,
    VOLCANOBADGE = 1,
  },
  lastHeal = {
    map = "CELADON_CITY",
    x = 32,
    y = 20,
  },
  lastOutdoor = {
    id = "CELADON_CITY",
    x = 32,
    y = 20,
  },
  meta = {
    format = 4,
    mods = {
      [1] = {
        api = 2,
        id = "DRAMATIC_SHAPE",
        version = "1.5.5",
      },
      [2] = {
        api = 1,
        id = "example_mew_starter",
        version = "1.0.0",
      },
      [3] = {
        api = 2,
        id = "nuzlocke",
        version = "1.0.0",
      },
    },
    modProfiles = {},
    modProfilesSeeded = false,
    modUpdateCache = {},
    mods = {
      DRAMATIC_SHAPE = true,
      example_mew_starter = false,
      nuzlocke = false,
    },
    musicFilter = 0,
    musicVol = 7,
    performance = "high",
    pikaVol = 7,
    pipelines = {
      tiltshift = 1,
      voxel = 4,
    },
    ruleset = "gen1_faithful",
    sfxVol = 7,
    speed = 1,
    textSpeed = 3,
    tilt = 0,
    touchControls = {
      enabled = true,
    },
    uiLayout = "centered",
    videoMode = "windowed",
    voidFill = "trees",
    zoom = 0,
  },
  party = {
    [1] = {
      catchRate = 60,
      dvs = {
        attack = 1,
        defense = 0,
        hp = 11,
        special = 9,
        speed = 15,
      },
      exp = 156250,
      hp = 176,
      level = 50,
      moves = {
        [1] = {
          id = "STOMP",
          pp = 20,
        },
        [2] = {
          id = "TAIL_WHIP",
          pp = 30,
        },
        [3] = {
          id = "FURY_ATTACK",
          pp = 20,
        },
        [4] = {
          id = "HORN_DRILL",
          pp = 5,
        },
      },
      ot = "BASTION",
      otId = 40555,
      species = "RHYDON",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 136,
        defense = 125,
        hp = 176,
        special = 59,
        speed = 60,
      },
    },
    [2] = {
      catchRate = 45,
      dvs = {
        attack = 7,
        defense = 4,
        hp = 10,
        special = 12,
        speed = 15,
      },
      exp = 117360,
      hp = 150,
      level = 50,
      moves = {
        [1] = {
          id = "SELFDESTRUCT",
          pp = 5,
        },
        [2] = {
          id = "HARDEN",
          pp = 30,
        },
        [3] = {
          id = "EARTHQUAKE",
          pp = 10,
        },
        [4] = {
          id = "EXPLOSION",
          pp = 5,
        },
      },
      ot = "BASTION",
      otId = 40555,
      species = "GOLEM",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 122,
        defense = 139,
        hp = 150,
        special = 72,
        speed = 65,
      },
    },
    [3] = {
      catchRate = 45,
      dvs = {
        attack = 7,
        defense = 7,
        hp = 13,
        special = 5,
        speed = 14,
      },
      exp = 117360,
      hp = 154,
      level = 50,
      moves = {
        [1] = {
          id = "TACKLE",
          pp = 35,
        },
        [2] = {
          id = "HORN_ATTACK",
          pp = 25,
        },
        [3] = {
          id = "POISON_STING",
          pp = 35,
        },
        [4] = {
          id = "THRASH",
          pp = 20,
        },
      },
      ot = "BASTION",
      otId = 40555,
      species = "NIDOKING",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 104,
        defense = 89,
        hp = 154,
        special = 85,
        speed = 104,
      },
    },
    [4] = {
      catchRate = 90,
      dvs = {
        attack = 1,
        defense = 9,
        hp = 15,
        special = 11,
        speed = 9,
      },
      exp = 125000,
      hp = 150,
      level = 50,
      moves = {
        [1] = {
          id = "SLASH",
          pp = 20,
        },
        [2] = {
          id = "POISON_STING",
          pp = 35,
        },
        [3] = {
          id = "SWIFT",
          pp = 20,
        },
        [4] = {
          id = "FURY_SWIPES",
          pp = 15,
        },
      },
      ot = "BASTION",
      otId = 40555,
      species = "SANDSLASH",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 106,
        defense = 124,
        hp = 150,
        special = 71,
        speed = 79,
      },
    },
    [5] = {
      catchRate = 50,
      dvs = {
        attack = 5,
        defense = 15,
        hp = 15,
        special = 5,
        speed = 7,
      },
      exp = 125000,
      hp = 110,
      level = 50,
      moves = {
        [1] = {
          id = "DIG",
          pp = 10,
        },
        [2] = {
          id = "SAND_ATTACK",
          pp = 15,
        },
        [3] = {
          id = "SLASH",
          pp = 20,
        },
        [4] = {
          id = "EARTHQUAKE",
          pp = 10,
        },
      },
      ot = "BASTION",
      otId = 40555,
      species = "DUGTRIO",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 90,
        defense = 70,
        hp = 110,
        special = 80,
        speed = 132,
      },
    },
    [6] = {
      catchRate = 45,
      dvs = {
        attack = 2,
        defense = 1,
        hp = 4,
        special = 2,
        speed = 4,
      },
      exp = 125000,
      hp = 99,
      level = 50,
      moves = {
        [1] = {
          id = "ROCK_THROW",
          pp = 15,
        },
        [2] = {
          id = "RAGE",
          pp = 20,
        },
        [3] = {
          id = "SLAM",
          pp = 20,
        },
        [4] = {
          id = "HARDEN",
          pp = 30,
        },
      },
      ot = "BASTION",
      otId = 40555,
      species = "ONIX",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 52,
        defense = 166,
        hp = 99,
        special = 37,
        speed = 79,
      },
    },
  },
  pcItems = {
    POTION = 1,
  },
  playTime = 90000,
  player = {
    facing = "down",
    id = 40555,
    map = "CELADON_CITY",
    name = "BASTION",
    rival = "GARY",
    surfing = false,
    x = 32,
    y = 20,
  },
  pokedex = {
    owned = {
      DUGTRIO = true,
      GOLEM = true,
      NIDOKING = true,
      ONIX = true,
      RHYDON = true,
      SANDSLASH = true,
    },
    seen = {
      DUGTRIO = true,
      GOLEM = true,
      NIDOKING = true,
      ONIX = true,
      RHYDON = true,
      SANDSLASH = true,
    },
  },
  repelSteps = 0,
  version = "red",
  visited = {
    CELADON_CITY = true,
    CERULEAN_CITY = true,
    CINNABAR_ISLAND = true,
    FUCHSIA_CITY = true,
    LAVENDER_TOWN = true,
    PALLET_TOWN = true,
    PEWTER_CITY = true,
    SAFFRON_CITY = true,
    VERMILION_CITY = true,
    VIRIDIAN_CITY = true,
  },
}
