return {
  box = {},
  defeatedTrainers = {},
  flags = {},
  inventory = {
    BICYCLE = 1,
    BOULDERBADGE = 1,
    CASCADEBADGE = 1,
    EARTHBADGE = 1,
    FULL_HEAL = 10,
    FULL_RESTORE = 20,
    HM01 = 1,
    HM02 = 1,
    HM03 = 1,
    HM04 = 1,
    HM05 = 1,
    MARSHBADGE = 1,
    MAX_POTION = 20,
    RAINBOWBADGE = 1,
    RARE_CANDY = 10,
    REVIVE = 10,
    SOULBADGE = 1,
    THUNDERBADGE = 1,
    ULTRA_BALL = 30,
    VOLCANOBADGE = 1,
  },
  lastHeal = {
    map = "CELADON_CITY",
    x = 28,
    y = 20,
  },
  lastOutdoor = {
    id = "CELADON_CITY",
    x = 28,
    y = 20,
  },
  meta = {
    format = 4,
    mods = {
      [1] = {
        api = 2,
        id = "DRAMATIC_SHAPE",
        version = "1.5.5",
      },
      [2] = {
        api = 1,
        id = "example_mew_starter",
        version = "1.0.0",
      },
      [3] = {
        api = 2,
        id = "nuzlocke",
        version = "1.0.0",
      },
    },
    modProfiles = {},
    modProfilesSeeded = false,
    modUpdateCache = {},
    mods = {
      DRAMATIC_SHAPE = true,
      example_mew_starter = false,
      nuzlocke = false,
    },
    musicFilter = 0,
    musicVol = 7,
    performance = "high",
    pikaVol = 7,
    pipelines = {
      tiltshift = 1,
      voxel = 4,
    },
    ruleset = "gen1_faithful",
    sfxVol = 7,
    speed = 1,
    textSpeed = 3,
    tilt = 0,
    touchControls = {
      enabled = true,
    },
    uiLayout = "centered",
    videoMode = "windowed",
    voidFill = "trees",
    zoom = 0,
  },
  party = {
    [1] = {
      catchRate = 45,
      dvs = {
        attack = 15,
        defense = 10,
        hp = 9,
        special = 7,
        speed = 10,
      },
      exp = 117360,
      hp = 147,
      level = 50,
      moves = {
        [1] = {
          id = "LEER",
          pp = 30,
        },
        [2] = {
          id = "RAGE",
          pp = 20,
        },
        [3] = {
          id = "SLASH",
          pp = 20,
        },
        [4] = {
          id = "FLAMETHROWER",
          pp = 15,
        },
      },
      ot = "BRASA",
      otId = 40111,
      species = "CHARIZARD",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 104,
        defense = 93,
        hp = 147,
        special = 97,
        speed = 115,
      },
    },
    [2] = {
      catchRate = 75,
      dvs = {
        attack = 1,
        defense = 6,
        hp = 8,
        special = 6,
        speed = 14,
      },
      exp = 156250,
      hp = 158,
      level = 50,
      moves = {
        [1] = {
          id = "ROAR",
          pp = 20,
        },
        [2] = {
          id = "EMBER",
          pp = 25,
        },
        [3] = {
          id = "LEER",
          pp = 30,
        },
        [4] = {
          id = "TAKE_DOWN",
          pp = 20,
        },
      },
      ot = "BRASA",
      otId = 40111,
      species = "ARCANINE",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 116,
        defense = 91,
        hp = 158,
        special = 91,
        speed = 114,
      },
    },
    [3] = {
      catchRate = 45,
      dvs = {
        attack = 10,
        defense = 6,
        hp = 2,
        special = 6,
        speed = 1,
      },
      exp = 117360,
      hp = 152,
      level = 50,
      moves = {
        [1] = {
          id = "LOW_KICK",
          pp = 20,
        },
        [2] = {
          id = "LEER",
          pp = 30,
        },
        [3] = {
          id = "FOCUS_ENERGY",
          pp = 30,
        },
        [4] = {
          id = "SEISMIC_TOSS",
          pp = 20,
        },
      },
      ot = "BRASA",
      otId = 40111,
      species = "MACHAMP",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 145,
        defense = 91,
        hp = 152,
        special = 76,
        speed = 61,
      },
    },
    [4] = {
      catchRate = 60,
      dvs = {
        attack = 11,
        defense = 1,
        hp = 14,
        special = 4,
        speed = 13,
      },
      exp = 156250,
      hp = 179,
      level = 50,
      moves = {
        [1] = {
          id = "STOMP",
          pp = 20,
        },
        [2] = {
          id = "TAIL_WHIP",
          pp = 30,
        },
        [3] = {
          id = "FURY_ATTACK",
          pp = 20,
        },
        [4] = {
          id = "HORN_DRILL",
          pp = 5,
        },
      },
      ot = "BRASA",
      otId = 40111,
      species = "RHYDON",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 146,
        defense = 126,
        hp = 179,
        special = 54,
        speed = 58,
      },
    },
    [5] = {
      catchRate = 25,
      dvs = {
        attack = 3,
        defense = 7,
        hp = 13,
        special = 1,
        speed = 6,
      },
      exp = 156250,
      hp = 233,
      level = 50,
      moves = {
        [1] = {
          id = "REST",
          pp = 10,
        },
        [2] = {
          id = "BODY_SLAM",
          pp = 15,
        },
        [3] = {
          id = "HARDEN",
          pp = 30,
        },
        [4] = {
          id = "DOUBLE_EDGE",
          pp = 15,
        },
      },
      ot = "BRASA",
      otId = 40111,
      species = "SNORLAX",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 118,
        defense = 77,
        hp = 233,
        special = 71,
        speed = 41,
      },
    },
    [6] = {
      catchRate = 45,
      dvs = {
        attack = 11,
        defense = 7,
        hp = 14,
        special = 14,
        speed = 11,
      },
      exp = 156250,
      hp = 149,
      level = 50,
      moves = {
        [1] = {
          id = "STOMP",
          pp = 20,
        },
        [2] = {
          id = "TAIL_WHIP",
          pp = 30,
        },
        [3] = {
          id = "LEER",
          pp = 30,
        },
        [4] = {
          id = "RAGE",
          pp = 20,
        },
      },
      ot = "BRASA",
      otId = 40111,
      species = "TAUROS",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 116,
        defense = 107,
        hp = 149,
        special = 89,
        speed = 126,
      },
    },
  },
  pcItems = {
    POTION = 1,
  },
  playTime = 75600,
  player = {
    facing = "down",
    id = 40111,
    map = "CELADON_CITY",
    name = "BRASA",
    rival = "GARY",
    surfing = false,
    x = 28,
    y = 20,
  },
  pokedex = {
    owned = {
      ARCANINE = true,
      CHARIZARD = true,
      MACHAMP = true,
      RHYDON = true,
      SNORLAX = true,
      TAUROS = true,
    },
    seen = {
      ARCANINE = true,
      CHARIZARD = true,
      MACHAMP = true,
      RHYDON = true,
      SNORLAX = true,
      TAUROS = true,
    },
  },
  repelSteps = 0,
  version = "red",
  visited = {
    CELADON_CITY = true,
    CERULEAN_CITY = true,
    CINNABAR_ISLAND = true,
    FUCHSIA_CITY = true,
    LAVENDER_TOWN = true,
    PALLET_TOWN = true,
    PEWTER_CITY = true,
    SAFFRON_CITY = true,
    VERMILION_CITY = true,
    VIRIDIAN_CITY = true,
  },
}
