return {
  box = {},
  defeatedTrainers = {},
  flags = {},
  inventory = {
    BICYCLE = 1,
    BOULDERBADGE = 1,
    CASCADEBADGE = 1,
    EARTHBADGE = 1,
    FULL_HEAL = 10,
    FULL_RESTORE = 20,
    HM01 = 1,
    HM02 = 1,
    HM03 = 1,
    HM04 = 1,
    HM05 = 1,
    MARSHBADGE = 1,
    MAX_POTION = 20,
    RAINBOWBADGE = 1,
    RARE_CANDY = 10,
    REVIVE = 10,
    SOULBADGE = 1,
    THUNDERBADGE = 1,
    ULTRA_BALL = 30,
    VOLCANOBADGE = 1,
  },
  lastHeal = {
    map = "CELADON_CITY",
    x = 30,
    y = 20,
  },
  lastOutdoor = {
    id = "CELADON_CITY",
    x = 30,
    y = 20,
  },
  meta = {
    format = 4,
    mods = {
      [1] = {
        api = 2,
        id = "DRAMATIC_SHAPE",
        version = "1.5.5",
      },
      [2] = {
        api = 1,
        id = "example_mew_starter",
        version = "1.0.0",
      },
      [3] = {
        api = 2,
        id = "nuzlocke",
        version = "1.0.0",
      },
    },
    modProfiles = {},
    modProfilesSeeded = false,
    modUpdateCache = {},
    mods = {
      DRAMATIC_SHAPE = true,
      example_mew_starter = false,
      nuzlocke = false,
    },
    musicFilter = 0,
    musicVol = 7,
    performance = "high",
    pikaVol = 7,
    pipelines = {
      tiltshift = 1,
      voxel = 4,
    },
    ruleset = "gen1_faithful",
    sfxVol = 7,
    speed = 1,
    textSpeed = 3,
    tilt = 0,
    touchControls = {
      enabled = true,
    },
    uiLayout = "centered",
    videoMode = "windowed",
    voidFill = "trees",
    zoom = 0,
  },
  party = {
    [1] = {
      catchRate = 45,
      dvs = {
        attack = 1,
        defense = 15,
        hp = 15,
        special = 11,
        speed = 9,
      },
      exp = 156250,
      hp = 205,
      level = 50,
      moves = {
        [1] = {
          id = "BODY_SLAM",
          pp = 15,
        },
        [2] = {
          id = "CONFUSE_RAY",
          pp = 10,
        },
        [3] = {
          id = "ICE_BEAM",
          pp = 10,
        },
        [4] = {
          id = "HYDRO_PUMP",
          pp = 5,
        },
      },
      ot = "MAREA",
      otId = 40333,
      species = "LAPRAS",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 91,
        defense = 100,
        hp = 205,
        special = 111,
        speed = 74,
      },
    },
    [2] = {
      catchRate = 60,
      dvs = {
        attack = 8,
        defense = 9,
        hp = 4,
        special = 6,
        speed = 4,
      },
      exp = 156250,
      hp = 124,
      level = 50,
      moves = {
        [1] = {
          id = "TACKLE",
          pp = 35,
        },
        [2] = {
          id = "WATER_GUN",
          pp = 25,
        },
        [3] = {
          id = "HARDEN",
          pp = 30,
        },
      },
      ot = "MAREA",
      otId = 40333,
      species = "STARMIE",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 88,
        defense = 99,
        hp = 124,
        special = 111,
        speed = 124,
      },
    },
    [3] = {
      catchRate = 60,
      dvs = {
        attack = 14,
        defense = 11,
        hp = 7,
        special = 1,
        speed = 7,
      },
      exp = 156250,
      hp = 117,
      level = 50,
      moves = {
        [1] = {
          id = "SUPERSONIC",
          pp = 20,
        },
        [2] = {
          id = "CLAMP",
          pp = 10,
        },
        [3] = {
          id = "AURORA_BEAM",
          pp = 20,
        },
        [4] = {
          id = "SPIKE_CANNON",
          pp = 15,
        },
      },
      ot = "MAREA",
      otId = 40333,
      species = "CLOYSTER",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 114,
        defense = 196,
        hp = 117,
        special = 91,
        speed = 82,
      },
    },
    [4] = {
      catchRate = 45,
      dvs = {
        attack = 13,
        defense = 1,
        hp = 13,
        special = 1,
        speed = 12,
      },
      exp = 156250,
      hp = 168,
      level = 50,
      moves = {
        [1] = {
          id = "BITE",
          pp = 25,
        },
        [2] = {
          id = "DRAGON_RAGE",
          pp = 10,
        },
        [3] = {
          id = "LEER",
          pp = 30,
        },
        [4] = {
          id = "HYDRO_PUMP",
          pp = 5,
        },
      },
      ot = "MAREA",
      otId = 40333,
      species = "GYARADOS",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 143,
        defense = 85,
        hp = 168,
        special = 106,
        speed = 98,
      },
    },
    [5] = {
      catchRate = 45,
      dvs = {
        attack = 14,
        defense = 3,
        hp = 7,
        special = 13,
        speed = 3,
      },
      exp = 125000,
      hp = 197,
      level = 50,
      moves = {
        [1] = {
          id = "BITE",
          pp = 25,
        },
        [2] = {
          id = "ACID_ARMOR",
          pp = 40,
        },
        [3] = {
          id = "HAZE",
          pp = 30,
        },
        [4] = {
          id = "MIST",
          pp = 30,
        },
      },
      ot = "MAREA",
      otId = 40333,
      species = "VAPOREON",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 84,
        defense = 68,
        hp = 197,
        special = 128,
        speed = 73,
      },
    },
    [6] = {
      catchRate = 75,
      dvs = {
        attack = 12,
        defense = 3,
        hp = 5,
        special = 3,
        speed = 8,
      },
      exp = 125000,
      hp = 160,
      level = 50,
      moves = {
        [1] = {
          id = "GROWL",
          pp = 40,
        },
        [2] = {
          id = "WATER_GUN",
          pp = 25,
        },
        [3] = {
          id = "WITHDRAW",
          pp = 40,
        },
        [4] = {
          id = "AMNESIA",
          pp = 20,
        },
      },
      ot = "MAREA",
      otId = 40333,
      species = "SLOWBRO",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 92,
        defense = 118,
        hp = 160,
        special = 88,
        speed = 43,
      },
    },
  },
  pcItems = {
    POTION = 1,
  },
  playTime = 82800,
  player = {
    facing = "down",
    id = 40333,
    map = "CELADON_CITY",
    name = "MAREA",
    rival = "GARY",
    surfing = false,
    x = 30,
    y = 20,
  },
  pokedex = {
    owned = {
      CLOYSTER = true,
      GYARADOS = true,
      LAPRAS = true,
      SLOWBRO = true,
      STARMIE = true,
      VAPOREON = true,
    },
    seen = {
      CLOYSTER = true,
      GYARADOS = true,
      LAPRAS = true,
      SLOWBRO = true,
      STARMIE = true,
      VAPOREON = true,
    },
  },
  repelSteps = 0,
  version = "red",
  visited = {
    CELADON_CITY = true,
    CERULEAN_CITY = true,
    CINNABAR_ISLAND = true,
    FUCHSIA_CITY = true,
    LAVENDER_TOWN = true,
    PALLET_TOWN = true,
    PEWTER_CITY = true,
    SAFFRON_CITY = true,
    VERMILION_CITY = true,
    VIRIDIAN_CITY = true,
  },
}
