return {
  animations = true,
  battleBg = "white",
  battleFit = "fixed",
  battleLayout = "og",
  battleStyle = "shift",
  colors = "redpp",
  faithfulRes = 0,
  fpsCap = 60,
  gbcfx = 0,
  modIndexCache = {},
  modIndexes = {},
  modOptions = {
    DRAMATIC_SHAPE = {
      aa = 2,
      battleBack = false,
      battles = true,
      curve = 1,
      daytime = "cycle",
      grid = false,
      water = "full",
    },
  },
  modProfiles = {},
  modProfilesSeeded = false,
  modUpdateCache = {},
  mods = {
    DRAMATIC_SHAPE = true,
    example_mew_starter = false,
    nuzlocke = false,
  },
  musicFilter = 0,
  musicVol = 7,
  performance = "high",
  pikaVol = 7,
  pipelines = {
    tiltshift = 1,
    voxel = 4,
  },
  ruleset = "gen1_faithful",
  sfxVol = 7,
  speed = 1,
  textSpeed = 3,
  tilt = 0,
  touchControls = {
    enabled = true,
  },
  uiLayout = "centered",
  videoMode = "windowed",
  voidFill = "trees",
  zoom = 0,
}
