return {
  box = {},
  defeatedTrainers = {},
  flags = {},
  inventory = {
    BICYCLE = 1,
    BOULDERBADGE = 1,
    CASCADEBADGE = 1,
    EARTHBADGE = 1,
    FULL_HEAL = 10,
    FULL_RESTORE = 20,
    HM01 = 1,
    HM02 = 1,
    HM03 = 1,
    HM04 = 1,
    HM05 = 1,
    MARSHBADGE = 1,
    MAX_POTION = 20,
    RAINBOWBADGE = 1,
    RARE_CANDY = 10,
    REVIVE = 10,
    SOULBADGE = 1,
    THUNDERBADGE = 1,
    ULTRA_BALL = 30,
    VOLCANOBADGE = 1,
  },
  lastHeal = {
    map = "CELADON_CITY",
    x = 29,
    y = 20,
  },
  lastOutdoor = {
    id = "CELADON_CITY",
    x = 29,
    y = 20,
  },
  meta = {
    format = 4,
    mods = {
      [1] = {
        api = 2,
        id = "DRAMATIC_SHAPE",
        version = "1.5.5",
      },
      [2] = {
        api = 1,
        id = "example_mew_starter",
        version = "1.0.0",
      },
      [3] = {
        api = 2,
        id = "nuzlocke",
        version = "1.0.0",
      },
    },
    modProfiles = {},
    modProfilesSeeded = false,
    modUpdateCache = {},
    mods = {
      DRAMATIC_SHAPE = true,
      example_mew_starter = false,
      nuzlocke = false,
    },
    musicFilter = 0,
    musicVol = 7,
    performance = "high",
    pikaVol = 7,
    pipelines = {
      tiltshift = 1,
      voxel = 4,
    },
    ruleset = "gen1_faithful",
    sfxVol = 7,
    speed = 1,
    textSpeed = 3,
    tilt = 0,
    touchControls = {
      enabled = true,
    },
    uiLayout = "centered",
    videoMode = "windowed",
    voidFill = "trees",
    zoom = 0,
  },
  party = {
    [1] = {
      catchRate = 50,
      dvs = {
        attack = 8,
        defense = 10,
        hp = 3,
        special = 7,
        speed = 1,
      },
      exp = 117360,
      hp = 118,
      level = 50,
      moves = {
        [1] = {
          id = "PSYBEAM",
          pp = 20,
        },
        [2] = {
          id = "RECOVER",
          pp = 20,
        },
        [3] = {
          id = "PSYCHIC_M",
          pp = 10,
        },
        [4] = {
          id = "REFLECT",
          pp = 20,
        },
      },
      ot = "PSIQUE",
      otId = 40222,
      species = "ALAKAZAM",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 63,
        defense = 60,
        hp = 118,
        special = 147,
        speed = 126,
      },
    },
    [2] = {
      catchRate = 45,
      dvs = {
        attack = 8,
        defense = 11,
        hp = 6,
        special = 14,
        speed = 11,
      },
      exp = 117360,
      hp = 126,
      level = 50,
      moves = {
        [1] = {
          id = "CONFUSE_RAY",
          pp = 10,
        },
        [2] = {
          id = "NIGHT_SHADE",
          pp = 15,
        },
        [3] = {
          id = "HYPNOSIS",
          pp = 20,
        },
        [4] = {
          id = "DREAM_EATER",
          pp = 15,
        },
      },
      ot = "PSIQUE",
      otId = 40222,
      species = "GENGAR",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 78,
        defense = 76,
        hp = 126,
        special = 149,
        speed = 126,
      },
    },
    [3] = {
      catchRate = 45,
      dvs = {
        attack = 11,
        defense = 0,
        hp = 10,
        special = 10,
        speed = 15,
      },
      exp = 156250,
      hp = 165,
      level = 50,
      moves = {
        [1] = {
          id = "BARRAGE",
          pp = 20,
        },
        [2] = {
          id = "HYPNOSIS",
          pp = 20,
        },
        [3] = {
          id = "STOMP",
          pp = 20,
        },
      },
      ot = "PSIQUE",
      otId = 40222,
      species = "EXEGGUTOR",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 111,
        defense = 90,
        hp = 165,
        special = 140,
        speed = 75,
      },
    },
    [4] = {
      catchRate = 60,
      dvs = {
        attack = 8,
        defense = 1,
        hp = 4,
        special = 10,
        speed = 14,
      },
      exp = 156250,
      hp = 124,
      level = 50,
      moves = {
        [1] = {
          id = "TACKLE",
          pp = 35,
        },
        [2] = {
          id = "WATER_GUN",
          pp = 25,
        },
        [3] = {
          id = "HARDEN",
          pp = 30,
        },
      },
      ot = "PSIQUE",
      otId = 40222,
      species = "STARMIE",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 88,
        defense = 91,
        hp = 124,
        special = 115,
        speed = 134,
      },
    },
    [5] = {
      catchRate = 45,
      dvs = {
        attack = 14,
        defense = 3,
        hp = 5,
        special = 1,
        speed = 6,
      },
      exp = 125000,
      hp = 130,
      level = 50,
      moves = {
        [1] = {
          id = "THUNDER_WAVE",
          pp = 20,
        },
        [2] = {
          id = "DOUBLE_KICK",
          pp = 30,
        },
        [3] = {
          id = "AGILITY",
          pp = 30,
        },
        [4] = {
          id = "PIN_MISSILE",
          pp = 20,
        },
      },
      ot = "PSIQUE",
      otId = 40222,
      species = "JOLTEON",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 84,
        defense = 68,
        hp = 130,
        special = 116,
        speed = 141,
      },
    },
    [6] = {
      catchRate = 30,
      dvs = {
        attack = 9,
        defense = 2,
        hp = 10,
        special = 0,
        speed = 5,
      },
      exp = 100000,
      hp = 320,
      level = 50,
      moves = {
        [1] = {
          id = "GROWL",
          pp = 40,
        },
        [2] = {
          id = "MINIMIZE",
          pp = 20,
        },
        [3] = {
          id = "DEFENSE_CURL",
          pp = 40,
        },
        [4] = {
          id = "LIGHT_SCREEN",
          pp = 30,
        },
      },
      ot = "PSIQUE",
      otId = 40222,
      species = "CHANSEY",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 19,
        defense = 12,
        hp = 320,
        special = 110,
        speed = 60,
      },
    },
  },
  pcItems = {
    POTION = 1,
  },
  playTime = 79200,
  player = {
    facing = "down",
    id = 40222,
    map = "CELADON_CITY",
    name = "PSIQUE",
    rival = "GARY",
    surfing = false,
    x = 29,
    y = 20,
  },
  pokedex = {
    owned = {
      ALAKAZAM = true,
      CHANSEY = true,
      EXEGGUTOR = true,
      GENGAR = true,
      JOLTEON = true,
      STARMIE = true,
    },
    seen = {
      ALAKAZAM = true,
      CHANSEY = true,
      EXEGGUTOR = true,
      GENGAR = true,
      JOLTEON = true,
      STARMIE = true,
    },
  },
  repelSteps = 0,
  version = "red",
  visited = {
    CELADON_CITY = true,
    CERULEAN_CITY = true,
    CINNABAR_ISLAND = true,
    FUCHSIA_CITY = true,
    LAVENDER_TOWN = true,
    PALLET_TOWN = true,
    PEWTER_CITY = true,
    SAFFRON_CITY = true,
    VERMILION_CITY = true,
    VIRIDIAN_CITY = true,
  },
}
