return {
  box = {},
  defeatedTrainers = {},
  flags = {},
  inventory = {
    BICYCLE = 1,
    BOULDERBADGE = 1,
    CASCADEBADGE = 1,
    EARTHBADGE = 1,
    FULL_HEAL = 10,
    FULL_RESTORE = 20,
    HM01 = 1,
    HM02 = 1,
    HM03 = 1,
    HM04 = 1,
    HM05 = 1,
    MARSHBADGE = 1,
    MAX_POTION = 20,
    RAINBOWBADGE = 1,
    RARE_CANDY = 10,
    REVIVE = 10,
    SOULBADGE = 1,
    THUNDERBADGE = 1,
    ULTRA_BALL = 30,
    VOLCANOBADGE = 1,
  },
  lastHeal = {
    map = "CELADON_CITY",
    x = 31,
    y = 20,
  },
  lastOutdoor = {
    id = "CELADON_CITY",
    x = 31,
    y = 20,
  },
  meta = {
    format = 4,
    mods = {
      [1] = {
        api = 2,
        id = "DRAMATIC_SHAPE",
        version = "1.5.5",
      },
      [2] = {
        api = 1,
        id = "example_mew_starter",
        version = "1.0.0",
      },
      [3] = {
        api = 2,
        id = "nuzlocke",
        version = "1.0.0",
      },
    },
    modProfiles = {},
    modProfilesSeeded = false,
    modUpdateCache = {},
    mods = {
      DRAMATIC_SHAPE = true,
      example_mew_starter = false,
      nuzlocke = false,
    },
    musicFilter = 0,
    musicVol = 7,
    performance = "high",
    pikaVol = 7,
    pipelines = {
      tiltshift = 1,
      voxel = 4,
    },
    ruleset = "gen1_faithful",
    sfxVol = 7,
    speed = 1,
    textSpeed = 3,
    tilt = 0,
    touchControls = {
      enabled = true,
    },
    uiLayout = "centered",
    videoMode = "windowed",
    voidFill = "trees",
    zoom = 0,
  },
  party = {
    [1] = {
      catchRate = 3,
      dvs = {
        attack = 3,
        defense = 15,
        hp = 13,
        special = 15,
        speed = 6,
      },
      exp = 156250,
      hp = 163,
      level = 50,
      moves = {
        [1] = {
          id = "THUNDERSHOCK",
          pp = 30,
        },
        [2] = {
          id = "DRILL_PECK",
          pp = 20,
        },
      },
      ot = "TORMENTA",
      otId = 40444,
      species = "ZAPDOS",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 98,
        defense = 105,
        hp = 163,
        special = 145,
        speed = 111,
      },
    },
    [2] = {
      catchRate = 45,
      dvs = {
        attack = 8,
        defense = 6,
        hp = 2,
        special = 2,
        speed = 7,
      },
      exp = 125000,
      hp = 127,
      level = 50,
      moves = {
        [1] = {
          id = "THUNDER_WAVE",
          pp = 20,
        },
        [2] = {
          id = "DOUBLE_KICK",
          pp = 30,
        },
        [3] = {
          id = "AGILITY",
          pp = 30,
        },
        [4] = {
          id = "PIN_MISSILE",
          pp = 20,
        },
      },
      ot = "TORMENTA",
      otId = 40444,
      species = "JOLTEON",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 78,
        defense = 71,
        hp = 127,
        special = 117,
        speed = 142,
      },
    },
    [3] = {
      catchRate = 45,
      dvs = {
        attack = 3,
        defense = 12,
        hp = 10,
        special = 2,
        speed = 11,
      },
      exp = 156250,
      hp = 161,
      level = 50,
      moves = {
        [1] = {
          id = "THUNDER_WAVE",
          pp = 20,
        },
        [2] = {
          id = "AGILITY",
          pp = 30,
        },
        [3] = {
          id = "SLAM",
          pp = 20,
        },
        [4] = {
          id = "DRAGON_RAGE",
          pp = 10,
        },
      },
      ot = "TORMENTA",
      otId = 40444,
      species = "DRAGONITE",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 142,
        defense = 112,
        hp = 161,
        special = 107,
        speed = 96,
      },
    },
    [4] = {
      catchRate = 45,
      dvs = {
        attack = 7,
        defense = 15,
        hp = 15,
        special = 15,
        speed = 5,
      },
      exp = 156250,
      hp = 155,
      level = 50,
      moves = {
        [1] = {
          id = "AGILITY",
          pp = 30,
        },
        [2] = {
          id = "SUPERSONIC",
          pp = 20,
        },
        [3] = {
          id = "BITE",
          pp = 25,
        },
        [4] = {
          id = "TAKE_DOWN",
          pp = 20,
        },
      },
      ot = "TORMENTA",
      otId = 40444,
      species = "AERODACTYL",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 117,
        defense = 85,
        hp = 155,
        special = 80,
        speed = 140,
      },
    },
    [5] = {
      catchRate = 75,
      dvs = {
        attack = 4,
        defense = 1,
        hp = 5,
        special = 15,
        speed = 8,
      },
      exp = 125000,
      hp = 125,
      level = 50,
      moves = {
        [1] = {
          id = "THUNDERSHOCK",
          pp = 30,
        },
        [2] = {
          id = "GROWL",
          pp = 40,
        },
        [3] = {
          id = "THUNDER_WAVE",
          pp = 20,
        },
      },
      ot = "TORMENTA",
      otId = 40444,
      species = "RAICHU",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 99,
        defense = 61,
        hp = 125,
        special = 110,
        speed = 113,
      },
    },
    [6] = {
      catchRate = 90,
      dvs = {
        attack = 7,
        defense = 14,
        hp = 11,
        special = 3,
        speed = 9,
      },
      exp = 125000,
      hp = 136,
      level = 50,
      moves = {
        [1] = {
          id = "BITE",
          pp = 25,
        },
        [2] = {
          id = "SCREECH",
          pp = 40,
        },
        [3] = {
          id = "PAY_DAY",
          pp = 20,
        },
        [4] = {
          id = "FURY_SWIPES",
          pp = 15,
        },
      },
      ot = "TORMENTA",
      otId = 40444,
      species = "PERSIAN",
      statExp = {
        attack = 0,
        defense = 0,
        hp = 0,
        special = 0,
        speed = 0,
      },
      stats = {
        attack = 82,
        defense = 79,
        hp = 136,
        special = 73,
        speed = 129,
      },
    },
  },
  pcItems = {
    POTION = 1,
  },
  playTime = 86400,
  player = {
    facing = "down",
    id = 40444,
    map = "CELADON_CITY",
    name = "TORMENTA",
    rival = "GARY",
    surfing = false,
    x = 31,
    y = 20,
  },
  pokedex = {
    owned = {
      AERODACTYL = true,
      DRAGONITE = true,
      JOLTEON = true,
      PERSIAN = true,
      RAICHU = true,
      ZAPDOS = true,
    },
    seen = {
      AERODACTYL = true,
      DRAGONITE = true,
      JOLTEON = true,
      PERSIAN = true,
      RAICHU = true,
      ZAPDOS = true,
    },
  },
  repelSteps = 0,
  version = "red",
  visited = {
    CELADON_CITY = true,
    CERULEAN_CITY = true,
    CINNABAR_ISLAND = true,
    FUCHSIA_CITY = true,
    LAVENDER_TOWN = true,
    PALLET_TOWN = true,
    PEWTER_CITY = true,
    SAFFRON_CITY = true,
    VERMILION_CITY = true,
    VIRIDIAN_CITY = true,
  },
}
